---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prd-bar
  namespace: argocd
  finalizers:
     - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
     repoURL: https://github.com/josemiguelgomes/myapp.git
     targetRevision: HEAD
     path: environments/2.prd/my-app2
  destination:
     server: https://kubernetes.default.svc
  syncPolicy:
     automated:
        prune: true
        selfHeal: true
        allowEmpty: false
     syncOptions:
        - Validate=true
        - CreateNamespace=false
        - PruneProgagationPolicy=foreground
        - PruneLast=true
